import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Challenge Frontend X-data",
  description: "Generated by Santiago Martinez",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
